name: Update README

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/steps/-step.txt'
      - '.github/workflows/update-readme.yml'
      - 'README.md'

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current step
        id: get_step
        run: |
          CURRENT_STEP=$(cat .github/steps/-step.txt)
          echo "current_step=$CURRENT_STEP" >> $GITHUB_OUTPUT
          echo "Current step: $CURRENT_STEP"

      - name: Update README
        run: |
          STEP=${{ steps.get_step.outputs.current_step }}
          echo "Updating README to step $STEP"
          
          if [ "$STEP" -eq 10 ]; then
            echo "Updating to completion message"
            cp .github/steps/10-finish.md README.md
            
            # Update any relative links in the README
            sed -i 's#(\.\./#(#' README.md
            
            # Add a note at the top
            echo -e "<!-- This README is automatically generated by the update-readme workflow -->\n$(cat README.md)" > README.md
          else
            echo "No README update needed for step $STEP"
          fi

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || \
          (git commit -m "docs: update README for step ${{ steps.get_step.outputs.current_step }}" && \
           git push) || echo "No changes to commit"
